### ISSUE TITLE
How do I Producing a working ROM?

### ISSUE THREAD

**Issue by jobjojo** [nmikstas/dragon-warrior-disassembly#1]
![Screenshot 2024-06-04 213208](https://github.com/nmikstas/dragon-warrior-disassembly/assets/132441374/52cc26b0-72c8-40e4-9dc7-01ea86be7d86)

I was able to run Git Bash to assemble the source files.
But I have a question, how do I compile the ROM to Load it into an NES emulator?
I'm not that much familiar with assembly.
If you could provide/add a Dropbox file with the complied  ROM that would be great

ayub_@Yuber MINGW64 ~/Desktop
$ ^C

ayub_@Yuber MINGW64 ~/Desktop
$ cd ~/Desktop/DragonWarriorDisassembly

ayub_@Yuber MINGW64 ~/Desktop/DragonWarriorDisassembly
$../build_script

Deleting previous build files...

Assembling individual PRG banks...

Loading Header.asm
Assembly complete: 16 bytes output (0 code, 16 data, 0 filler)
Loading Bank00.asm
Loading Dragon_Warrior_Defines.asm
Assembly complete: 16384 bytes output (5377 code, 11007 data, 0 filler)
Loading Bank01.asm
Loading Dragon_Warrior_Defines.asm
Assembly complete: 16384 bytes output (5755 code, 10629 data, 0 filler)
Loading Bank02.asm
Loading Dragon_Warrior_Defines.asm
Assembly complete: 16384 bytes output (324 code, 16060 data, 0 filler)
Loading Bank03.asm
Loading Dragon_Warrior_Defines.asm
Assembly complete: 16384 bytes output (13287 code, 3097 data, 0 filler)

Calculating checksums of individual PRG banks...

--------------------PRG Bank 00--------------------
Assembled md5sum = 4494467c3c7f3401a5ea25947814b8bd
Original  md5sum = 4494467c3c7f3401a5ea25947814b8bd
Pass

--------------------PRG Bank 01--------------------
Assembled md5sum = e34c39bfb3069bc6c563b0e614b22a49
Original  md5sum = e34c39bfb3069bc6c563b0e614b22a49
Pass

--------------------PRG Bank 02--------------------
Assembled md5sum = 0135d12602c3efb5728a0f220ae916fd
Original  md5sum = 0135d12602c3efb5728a0f220ae916fd
Pass

--------------------PRG Bank 03--------------------
Assembled md5sum = aae638b52ffc7a720a63d6ef1700a2b3
Original  md5sum = aae638b52ffc7a720a63d6ef1700a2b3
Pass

ayub_@Yuber MINGW64 ~/Desktop/DragonWarriorDisassembly

**Comment by nmikstas** [comment]
Add both attached files to the DragonWarriorDisassembly folder. The new
build_script will overwrite the original build_script. run the new
build_script. There is an extra segment of code at the end that will
combine all the files into a functional ROM. The CHR_ROM.bin file is all
the graphical data for the game. Let me know if this works.

Nick

**Comment by jobjojo** [comment]
Thanks for the replying. 
My bad for asking bro again.
But what two files am I supposed to attach to "DragonWarriorDisassembly" folder. 
Am I supposed to download both a "new " build_script  and "CHR_ROM.bin"  file ?
I don't see any attached files or links from your reply ( or will these be added to the repo ?).

Besides that , I understand everything else about running the new build_script in Git bash to combine all files into a functional ROM 

Here how everything looks in my DragonWarriorDisassembly folder:
![image](https://github.com/nmikstas/dragon-warrior-disassembly/assets/132441374/b7f2bbd6-1e2b-43c6-b2e0-ab2a8ca9d0df)
![image](https://github.com/nmikstas/dragon-warrior-disassembly/assets/132441374/9f0c0b68-33c5-4fd1-ae27-e3d0bcabeaa3)
![image](https://github.com/nmikstas/dragon-warrior-disassembly/assets/132441374/a162a204-3f9c-431c-bfeb-8ec915d08525)

**Comment by nmikstas** [comment]
I attached 2 files to the email. Github may have removed them. Do you have
a shared drive link or an alternate email address?

**Comment by jobjojo** [comment]
hansolu0002@gmail.com
https://drive.google.com/drive/folders/1U3rwoYRW9Udjz7LALKaYzmiHg7Tx67oM?usp=sharing

**Comment by nmikstas** [comment]
I sent you an email. It says I don't have permission to upload to that
drive.

**Comment by jobjojo** [comment]
No problem.
I got the files.

It works like Dreams in the emulator 
You, Sir, are a 👑.

Take care, brother. 

![image](https://github.com/nmikstas/dragon-warrior-disassembly/assets/132441374/c11fe0e2-7465-4c5e-ab7a-daeb8e00cf45)

**Comment by nmikstas** [comment]
Nice! Let me know if you do anything cool with it!
